// ACTIONS
export const LIST_STUDENTS = "LIST_STUDENTS";

// SAGAS
export const LIST_STUDENTS_SAGAS = "LIST_STUDENTS_SAGAS";
export const CHANGE_STUDENT_STATUS_SAGAS = "CHANGE_STUDENT_STATUS_SAGAS";
export const REMOVE_STUDENT_SAGAS = "REMOVE_STUDENT_SAGAS";
export const ADD_STUDENT_SAGAS = "ADD_STUDENT_SAGAS";