// ACTIONS
export const LIST_DISCIPLINE = "LIST_DISCIPLINE";
export const LIST_ALL_DISCIPLINES = "LIST_ALL_DISCIPLINES";

// SAGAS
export const LIST_DISCIPLINE_SAGAS = "LIST_DISCIPLINE_SAGAS";
export const CREATE_DISCIPLINE_SAGAS = "CREATE_DISCIPLINE_SAGAS";
export const UPDATE_DISCIPLINE_SAGAS = "UPDATE_DISCIPLINE_SAGAS";
export const DELETE_DISCIPLINE_SAGAS = "DELETE_DISCIPLINE_SAGAS";
export const LIST_ALL_DISCIPLINE_SAGAS = "LIST_ALL_DISCIPLINE_SAGAS";
export const ENTER_DISCIPLINE_SAGAS = "ENTER_DISCIPLINE_SAGAS";