// ACTIONS
export const LIST_DISCIPLINE = "LIST_DISCIPLINE";
export const LIST_ALL_DISCIPLINES = "LIST_ALL_DISCIPLINES";
export const FETCH_DISCIPLINE = "FETCH_DISCIPLINE";

// SAGAS
export const LIST_DISCIPLINE_SAGAS = "LIST_DISCIPLINE_SAGAS";
export const FETCH_DISCIPLINE_SAGAS = "FETCH_DISCIPLINE_SAGAS";
export const CREATE_DISCIPLINE_SAGAS = "CREATE_DISCIPLINE_SAGAS";
export const UPDATE_DISCIPLINE_SAGAS = "UPDATE_DISCIPLINE_SAGAS";
export const DELETE_DISCIPLINE_SAGAS = "DELETE_DISCIPLINE_SAGAS";
export const LIST_ALL_DISCIPLINE_SAGAS = "LIST_ALL_DISCIPLINE_SAGAS";
export const ENTER_DISCIPLINE_SAGAS = "ENTER_DISCIPLINE_SAGAS";
export const RESET_DISCIPLINE_SAGAS = "RESET_DISCIPLINE_SAGAS";
export const TOOGLE_DISCIPLINE_STATUS_SAGAS = "TOOGLE_DISCIPLINE_STATUS_SAGAS";