// ACTIONS
export const LIST_DISCIPLINE = "LIST_DISCIPLINE";

// SAGAS
export const LIST_DISCIPLINE_SAGAS = "LIST_DISCIPLINE_SAGAS";
export const CREATE_DISCIPLINE_SAGAS = "CREATE_DISCIPLINE_SAGAS";
export const UPDATE_DISCIPLINE_SAGAS = "UPDATE_DISCIPLINE_SAGAS";
export const DELETE_DISCIPLINE_SAGAS = "DELETE_DISCIPLINE_SAGAS";