const QUESTION_TYPE = {
    V_OR_F: "V_OR_F",
    MULTIPLE_CHOICES: "MULTIPLE_CHOICES",
    SHOT: "SHOT"
}

const QUESTION_EXAM = {
    EXERCISE: "EXERCISE",
    TRADITIONAL: "TRADITIONAL",
    TBL: "TBL"
}

export {QUESTION_TYPE, QUESTION_EXAM};