// ACTIONS
export const LIST_QUESTIONS = "LIST_QUESTIONS";
export const FETCH_QUESTION = "FETCH_QUESTION";
export const RESULT_ACTION = "RESULT_ACTION";

// SAGAS
export const LIST_QUESTIONS_SAGAS = "LIST_QUESTIONS_SAGAS";
export const CREATE_QUESTION_SAGAS = "CREATE_QUESTION_SAGAS";
export const UPDATE_QUESTION_SAGAS = "UPDATE_QUESTION_SAGAS";
export const DELETE_QUESTION_SAGAS = "DELETE_QUESTION_SAGAS";
export const SUBMIT_SAGAS = "SUBMIT_SAGAS";
export const RESULT_SAGAS = "RESULT_SAGAS";