// ACTIONS
export const LIST_GROUPS = "LIST_GROUPS";
export const UPDATE_FORM = "UPDATE_FORM";

// SAGAS
export const LIST_GROUPS_SAGAS = "LIST_GROUPS_SAGAS";
export const CREATE_GROUP_SAGAS = "CREATE_GROUP_SAGAS";
export const UPDATE_GROUP_SAGAS = "UPDATE_GROUP_SAGAS";
export const DELETE_GROUP_SAGAS = "DELETE_GROUP_SAGAS";
export const PROVIDE_GROUP_SAGAS = "PROVIDE_GROUP_SAGAS";
export const ADD_STUDENT_GROUP_SAGAS = "ADD_STUDENT_GROUP_SAGAS";
export const REMOVE_STUDENT_GROUP_SAGAS = "REMOVE_STUDENT_GROUP_SAGAS";