// ACTIONS
export const LIST_SECTIONS = "LIST_SECTIONS";
export const UPDATE_FORM = "UPDATE_FORM";

// SAGAS
export const LIST_SECTIONS_SAGAS = "LIST_SECTIONS_SAGAS";
export const CREATE_SECTION_SAGAS = "CREATE_SECTION_SAGAS";
export const UPDATE_SECTION_SAGAS = "UPDATE_SECTION_SAGAS";
export const DELETE_SECTION_SAGAS = "DELETE_SECTION_SAGAS";
export const PROVIDE_SECTION_SAGAS = "PROVIDE_SECTION_SAGAS";
export const FINISH_SECTION_SAGAS = "FINISH_SECTION_SAGAS";